- name: allow port
  hosts: workers
  become: yes

  tasks:
    - name: allow port
      community.general.ufw:
        port: 30000:32647
        rule: allow
        proto: tcp
    - name: allow port 2
      community.general.ufw:
        port: 10250
        rule: allow
        proto: tcp

- name: allow port2
  hosts: masters
  become: yes

  tasks:
    - name: allow port2
      community.general.ufw:
        port: 10250:10252
        rule: allow
        proto: tcp
    - name: allow-port2
      community.general.ufw:
        port: 6443
        rule: allow
        proto: tcp
    - name: allowport2
      community.general.ufw:
        port: 2379:2380
        rule: allow
        proto: tcp
- name: daemon-reload
  hosts: masters,workers
  become: yes


  tasks:
    - name: daemon-reload
      ansible.builtin.systemd_service:
        daemon_reload: true
