- name: install kubectl
  hosts: Jenkins
  become: yes

  tasks:
    - name: add certificate
      ansible.builtin.shell: apt install -y apt-transport-https ca-certificates curl
    - name: add gpg key
      ansible.builtin.shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | gpg  --dearmor --yes -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    - name: add repo
      ansible.builtin.shell: echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list


    - name: update package
      ansible.builtin.apt:
        update_cache: yes
    - name: install kubectl
      ansible.builtin.shell: apt install kubectl -y
